### ISSUE TITLE
Enhance Nostr Login

### ISSUE THREAD

**Issue by oreHGA** [NEUROFUSIONInc/fusion#193]
- When a person signs in, we currently save their private key to localstorage, need to decide if we want to delete this on logout? I like it as is now but if I want to switch to using nos2x, I have to manually go delete from localStorage, not ideal ... however, I think this will no longer be an issue when we do this:

----

On the login page, we have the following options:

```
So by default you'd see :
- Continue as Guest
---
and then:
- Use Browser Extension
- Use Account Key
```

- [x] If you click continue as guest, we use nip04 as implemented in #189:
  - if there's already a privateKey in localStorage, it means you're not really a guest you already had an account before - I think we should reuse account.
  - if not we autogenerate a nostr privateKey and then sign you in to Fusion

- [x] If you select `Use Browser Extension` we sign you in using nip07 as done in #189 
- [x] If you select `Use Account Key` we pop-up an input field for you to enter your private key and the we sign you in using nip04 as in #189 

----

**Comment by oreHGA** [comment]
screencap of how highlighter does theirs 
![image](https://github.com/NEUROFUSIONInc/fusion/assets/13490968/46c605fa-da95-4327-85ad-c47629651c92)

**Comment by jokonuko** [comment]
> When a person signs in, we currently save their private key to localstorage, need to decide if we want to delete this on logout? I like it as is now but if I want to switch to using nos2x, I have to manually go delete from localStorage, not ideal ... however, I think this will no longer be an issue when we do this:

Discussed offline and figured we can just keep the ephemeral keys in browser until a user decides to delete it (manually for now). Perhaps we can add a "Delete account" feature in the profile page?

**Comment by oreHGA** [comment]
> Perhaps we can add a "Delete account" feature in the profile page?

Yes I like this!
